/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_base_native1_HelloWorld */

#ifndef _Included_com_java_base_native1_HelloWorld
#define _Included_com_java_base_native1_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_base_native1_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_java_base_native1_HelloWorld_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
